version: '3'

services:

  # web server
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile

    depends_on: 
      - mysql
    ports:
      - "80:80"
    volumes:
      - "./html:/var/www/html"

  # database
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment: 
      MYSQL_DATABASE: cakedb
      MYSQL_USER: cakeuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0
    depends_on: 
      - mysql
    ports:
      - "8080:80"
    environment: 
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
